# Generated by Django 2.1.3 on 2019-01-23 11:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('adderss', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('sqft', models.IntegerField()),
                ('offers', models.CharField(help_text='enter Discount Percentage as 10% off', max_length=8)),
                ('photo_main', models.ImageField(upload_to='Photos/%Y/%M/%D')),
                ('photo_1', models.ImageField(blank=True, upload_to='Photos/%Y/%M/%D')),
                ('photo_2', models.ImageField(blank=True, upload_to='Photos/%Y/%M/%D')),
                ('photo_3', models.ImageField(blank=True, upload_to='Photos/%Y/%M/%D')),
                ('photo_4', models.ImageField(blank=True, upload_to='Photos/%Y/%M/%D')),
                ('photo_5', models.ImageField(blank=True, upload_to='Photos/%Y/%M/%D')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('types', models.CharField(choices=[('Apartments', 'Apartment'), ('Lands', 'Land'), ('villas', 'Villa'), ('Bars', 'Bar'), ('Stores', 'Store'), ('Farms', 'Farm')], default='Apartments', max_length=10)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor')),
            ],
        ),
    ]
